### ISSUE TITLE
User Stories: Authentication

### ISSUE THREAD

**Issue by chrissuttondev** [chrissuttondev/Barnets#10]
As a user, I want to create an account so that I can book appointments and manage my bookings
Acceptance criteria:

User should be able to provide basic information (name, email, phone number).
User should receive a verification email for account confirmation.
User should be able to log in with the created credentials.
User should be able to re-set account info if log in details are forgotten.

## Tasks
- [ ] Implement user registration form.
- [ ]  Develop email verification functionality.
- [ ] Create login page and authentication process.
- [ ] Redirect the user to booking form after registration and  / or log in
