### ISSUE TITLE
User Story: User - Create, cancel and update bookings

### ISSUE THREAD

**Issue by chrissuttondev** [chrissuttondev/Barnets#14]
As a user, I want to **reschedule or cancel appointments**, so that I can **effectively manage my schedule.**

Acceptance criteria:

User should be able to create cancel and  / or  reschedule and existing appointment.
Cancelled  appointment slot should become available for booking again.
User should receive confirmation upon successful cancellation or update.

## Tasks 

- [ ] Develop booking interface
- [ ] Create  data models
- [ ] Develop create, cancel and edit functionality for appointments.
- [ ] Update database upon successful cancellation or update.
- [ ] Ensure cancelled slots become available for booking.
- [ ] Send User email confirmation of new booking made and / or cancellation or update to prior bookings..
