### ISSUE TITLE
User Story: User - View Services Offered by Barbers:

### ISSUE THREAD

**Issue by chrissuttondev** [chrissuttondev/Barnets#16]
As a user, I want to see the list of services offered by each barber, so that I can, choose the service that are right for me. .

Acceptance criteria:

The app should display a list of services along with their descriptions.
User should be able to see which services are offered by each barber.

## Tasks
- [ ] Create barber service list .
- [ ] Populate service data for each barber.
- [ ] Ensure services are displayed accurately.
